# Generated by Django 5.0.7 on 2024-09-05 13:58

import Chatmate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatmate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='id',
            field=models.CharField(default=Chatmate.models.generate_random_id, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
