# Generated by Django 5.0.7 on 2024-09-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatmate', '0002_alter_rooms_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='Chatmate.rooms', to_field='name'),
        ),
    ]
