# Generated by Django 5.0.7 on 2024-09-07 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatmate', '0003_alter_query_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedchunk',
            name='room',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='combined_chunks', to='Chatmate.rooms', to_field='name'),
            preserve_default=False,
        ),
    ]
