# Generated by Django 5.0.7 on 2024-09-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
